apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.9-192.168.1.10-192.168.1.11-192.168.1.12-192.168.1.15-192.168.1.14-192.168.1.36
