apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-covid
  name: covid-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: covid-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-app
spec:
  selector:
    matchLabels:
      app: covid-app
  replicas: 5
  template:
    metadata:
      labels:
        app: covid-app
    spec:
      containers:
      - name: covid-app
        image: elminino/covid-front:0.0.8
        ports:
        - containerPort: 80
